"""Pydantic models for CareerFlow.

These models act as the **schema enforcer** layer (PydanticAI) ensuring that
every agent output is a perfectly-structured JSON payload that the Next.js
frontend can reliably render.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ── Persona taxonomy ──────────────────────────────────────────────────────────


class Persona(str, Enum):
    SOFTWARE_ENGINEERING = "software_engineering"
    PRODUCT_MANAGEMENT = "product_management"
    OPERATIONS_MARKETING = "operations_marketing"
    UI_UX_DESIGN = "ui_ux_design"


# ── Resume building blocks ────────────────────────────────────────────────────


class ExperienceEntry(BaseModel):
    title: str = Field(description="Job title or role")
    company: str = Field(description="Company or organisation name")
    start_date: str = Field(description="Start date (e.g. 'Jan 2023')")
    end_date: str = Field(description="End date or 'Present'")
    bullets: list[str] = Field(default_factory=list, description="Impact-driven bullet points")
    persona_tags: list[Persona] = Field(
        default_factory=list,
        description="Which personas this experience is relevant to",
    )


class EducationEntry(BaseModel):
    institution: str
    degree: str
    field_of_study: str
    graduation_year: int
    gpa: float | None = None
    highlights: list[str] = Field(default_factory=list)


class ProjectEntry(BaseModel):
    name: str
    description: str
    technologies: list[str] = Field(default_factory=list)
    persona_tags: list[Persona] = Field(default_factory=list)
    url: str | None = None


# ── Top-level document models ─────────────────────────────────────────────────


class Resume(BaseModel):
    """Structured resume ready for frontend rendering."""

    name: str
    email: str = ""
    phone: str = ""
    linkedin: str = ""
    github: str = ""
    website: str = ""
    summary: str = ""
    experience: list[ExperienceEntry] = Field(default_factory=list)
    education: list[EducationEntry] = Field(default_factory=list)
    projects: list[ProjectEntry] = Field(default_factory=list)
    skills: list[str] = Field(default_factory=list)
    persona: Persona | None = None


class CoverLetter(BaseModel):
    """Structured cover letter returned by the humanizer node."""

    company: str
    role: str
    prose: str = Field(
        description=(
            "Full cover letter text written as flowing prose. "
            "No bullet points. No corporate jargon."
        )
    )
    word_count: int = 0

    def model_post_init(self, __context: Any) -> None:
        if not self.word_count and self.prose:
            self.word_count = len(self.prose.split())


class InterviewQuestion(BaseModel):
    question: str
    category: str = Field(
        description="E.g. 'Behavioural', 'Technical', 'System Design', 'Product Sense'"
    )
    hint: str = ""


class InterviewScript(BaseModel):
    """Mock-interview script generated by the simulator node."""

    role: str
    company: str
    questions: list[InterviewQuestion] = Field(default_factory=list)
    prep_resources: list[str] = Field(default_factory=list)
    estimated_duration_minutes: int = 45


# ── Orchestration I/O ─────────────────────────────────────────────────────────


class OrchestrationRequest(BaseModel):
    """Input sent by the frontend to kick off the full pipeline."""

    job_description: str = Field(description="Raw job posting text")
    company: str = ""
    role: str = ""
    persona: Persona = Persona.SOFTWARE_ENGINEERING


class OrchestrationResponse(BaseModel):
    """Complete pipeline output returned to the frontend."""

    resume: Resume
    cover_letter: CoverLetter
    interview_script: InterviewScript
